### ISSUE TITLE
Fairness discussion

### ISSUE THREAD

**Issue by YvoGao** [BDBC-KG-NLP/AAAI2022_ContrastNet#3]
Why do the number of shots and the number of queries have to be the same? The number of queries in MLADA, DS-FSL, etc., is that fair?

**Comment by YvoGao** [comment]
There are two scores of acc and acc_knn in your code, and the acc score is used in the work using early stop, so should the acc score be used as the final result? What is acc_knn?

**Comment by AlbertChen1991** [comment]
> Why do the number of shots and the number of queries have to be the same? The number of queries in MLADA, DS-FSL, etc., is that fair?

The number of shots and the number of queries are not forced to be the same, but letting them same is a standard configuration in meta-learning, including in MLADA, DS-FSL, etc., it is of course fair using such same setting.

**Comment by AlbertChen1991** [comment]
> There are two scores of acc and acc_knn in your code, and the acc score is used in the work using early stop, so should the acc score be used as the final result? What is acc_knn?

acc_knn is the accuracy of using KNN classifier for prediction. It is the default results in the paper. acc is the accurcy of using softmax classifier for prediction. acc_knn is not always the best, so you may use softmax for prediction and regard acc as the final results.

**Comment by yunlong-G** [comment]
thank you for your reply

**Comment by YvoGao** [comment]
Thank you for your reply. Because I want to refer to your article as the baseline, when replicating your code for my task, I have questions about these two places of your code, thank you for your answer！ I took the same division and used the acc after averaging multiple seeds as the final result.

**Comment by YvoGao** [comment]
![image](https://github.com/BDBC-KG-NLP/AAAI2022_ContrastNet/assets/58680618/7fd33d31-a2c4-479b-8ea2-8399ce657835)
As shown in the red box, I want to express that if you used acc as the index to select the best model in your paper, should the final result also be based on the score of acc?

**Comment by AlbertChen1991** [comment]
> ![image](https://user-images.githubusercontent.com/58680618/260045724-7fd33d31-a2c4-479b-8ea2-8399ce657835.png) As shown in the red box, I want to express that if you used acc as the index to select the best model in your paper, should the final result also be based on the score of acc?

Thank you for your feedback. You are right. We may use the acc as the final results in our paper. I remember the acc and acc_knn results are similar, so it's ok to use either of them.
