### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by saynoer** [BDBC-KG-NLP/AAAI2022_ContrastNet#5]
为什么一直会有这个问题呢？cannot import name 'BartTokenizerFast' from 'transformers.models.auto.tokenization_auto' (D:\Python\Lib\site-packages\transformers\models\auto\tokenization_auto.py)

**Comment by AlbertChen1991** [comment]
可能是torch或transformer版本的问题，请按照对应的版本部署

**Comment by AlbertChen1991** [comment]
> 为什么一直会有这个问题呢？cannot import name 'BartTokenizerFast' from 'transformers.models.auto.tokenization_auto' (D:\Python\Lib\site-packages\transformers\models\auto\tokenization_auto.py)

可能是torch或transformer版本的问题，已增加requirements.txt文件，请按照该文件对应的版本部署

**Comment by xuer0916** [comment]
> 为什么一直会有这个问题呢？cannot import name 'BartTokenizerFast' from 'transformers.models.auto.tokenization_auto' (D:\Python\Lib\site-packages\transformers\models\auto\tokenization_auto.py)

你好，请问可以分享一下这篇论文的代码嘛，我想学习一下

**Comment by xuer0916** [comment]
> 可能是torch或transformer版本的问题，请按照对应的版本部署

你好，请问可以分享一下代码嘛。我想学习一下
